### ISSUE TITLE
 Check if the files defined in the 'offline' importScripts option actually exist

### ISSUE THREAD

**Issue by marco-c** [mozilla/oghliner#101]
Currently, we don't check if the files defined in _importScripts_ actually exist and we directly add the code to import them in the service worker.
We should check if they exist and throw an exception or print a warning message if they don't.

We could add this feature either to oghliner or sw-precache, @mykmelez what do you think? It really depends on whether we plan to remove the dependency on sw-precache in the future.

**Comment by marco-c** [comment]
Since I filed this, @lodr filed a PR to use offliner instead of sw-precache.

**Comment by delapuente** [comment]
It's still in progress. I hope to have it finished by this week.
