### ISSUE TITLE
Tests intermittently hang at the end

### ISSUE THREAD

**Issue by marco-c** [mozilla/oghliner#112]
After `Finished 'test' after 1.88 s`.

**Comment by brendandahl** [comment]
Still looking into this, but it seems to be something racey with await(). If I wait to resolve https://github.com/mozilla/oghliner/blob/9d7d3acbc838c72b3521bf81e3f623275653918c/test/testConfigure.js#L47 with a setTimeout the tests don't hang. I'm guessing we're emiting before we're listening for a prompt. Not sure yet how to properly fix though.

**Comment by marco-c** [comment]
There was another test hang that was caused by a race condition in await, but it made testConfigure hang. Instead now the tests are hanging after supposedly everything is finished.
