### ISSUE TITLE
oghliner declines to offline my 4MB CSV file

### ISSUE THREAD

**Issue by wfwalker** [mozilla/oghliner#125]
oghliner declines to offline my 4MB CSV file in http://wfwalker.github.io/ebird-mybird/

How can I reconfigure this to allow larger files?

[17:46:35] Skipping static resource "dist/data/ebird.csv" (4.41 MB) - max size is 2.1 MB

**Comment by marco-c** [comment]
Duplicate of #28.

**Comment by marco-c** [comment]
#127 will fix this problem.
