### ISSUE TITLE
clarify output of configure command

### ISSUE THREAD

**Issue by mykmelez** [mozilla/oghliner#148]
The _configure_ command's output should be clearer. This is part of #26. Here's a proposed redesign for the happiest path. Unfortunately, it isn't possible to set colors, but I would make the info section (which starts with a ℹ character) blue and the warning section (which starts with a ⚠ character) yellow and use some text formatting (color tone? bold weight?) to set apart the command example.

Each async operation message would also display a spinner to its right until it completes, at which point the text "done!" would replace it, and the checkmarks to the left of those messages would appear. We might color those checkmarks green, à la the checkmarks next to the test names in the test output.

```
Configuring Travis to auto-deploy [REPOSITORY SLUG] to GitHub Pages…

To check the status of your repository in Travis and authorize Travis to push
to it, I'll create GitHub personal access tokens, for which I need your GitHub
username and password (and two-factor authentication code, if appropriate).

ℹ For more information about GitHub personal access tokens, see:
    https://github.com/settings/tokens

Username: username
Password: 

You're using two-factor authentication with GitHub.
Please enter the code provided by your authentication software.

Auth Code: 123456

✓ Creating temporary GitHub token for getting Travis token… done!
✓ Getting Travis token… done!
✓ Deleting temporary GitHub token for getting Travis token… done!
✓ Creating permanent GitHub token for Travis to push to the repository… done!
✓ Checking the status of your repository in Travis… done!

Good news, your repository is already active in Travis!

✓ Encrypting permanent GitHub token… done!
✓ Writing configuration to .travis.yml file… done!

⚠ You didn't already have a .travis.yml file, so I created one for you.
  For more information about the file, see:
    http://docs.travis-ci.com/user/customizing-the-build/

You're ready to auto-deploy using Travis!  Just commit the changes
in .travis.yml and push the commit to the origin/master branch:

git commit -m"configure Travis to auto-deploy to GitHub Pages" .travis.yml
git push origin master

Then visit [TRAVIS BUILD URL FOR REPOSITORY] to see build status.
```

**Comment by marco-c** [comment]
Should we close #26 and file clearer issues like this one?

**Comment by mykmelez** [comment]
> Should we close #26 and file clearer issues like this one?

Yes, or simply file clearer issues and then use #26 as a meta-issue to track them, adding a checklist of issues to the description of #26. Unsure which makes more sense.

**Comment by marco-c** [comment]
Let's try it.
