### ISSUE TITLE
Release the generated service worker to the public domain

### ISSUE THREAD

**Issue by marco-c** [mozilla/oghliner#155]
#38 was about the template files, but I think we should also release the generated service worker to the public domain in order to let the developers choose their own license.

We can either do this by removing the sw-precache dependency and rolling our own service worker or by using the `templateFilePath` option [1] of sw-precache using our own service worker template.

[1] https://github.com/GoogleChrome/sw-precache#templatefilepath-string

I think @delapuente was looking into this, right?

**Comment by mykmelez** [comment]
Yes, @delapuente is looking into this!

**Comment by mykmelez** [comment]
@delapuente fixed this in #188!
