### ISSUE TITLE
Make *deploy* available from the command line interface

### ISSUE THREAD

**Issue by marco-c** [mozilla/oghliner#16]
This would make the oghliner _deploy_ functionality useful also when you only want the deploy functionality and you don't use Gulp but a Makefile or a npm script.

**Comment by mykmelez** [comment]
I have a work-in-progress for this.

**Comment by mykmelez** [comment]
https://github.com/mozilla/oghliner/commit/aaf270dee0e9b13d202679eaffbc074ea6a2abc7 does this, although I haven't yet updated the README.

**Comment by mykmelez** [comment]
https://github.com/mozilla/oghliner/commit/0235150198ff6082e9a2962d1713300239692778 adds the minimal documentation. I'm not sure this is quite the right interface, though. I wonder if it should be simply `oghliner deploy dist`.

**Comment by mykmelez** [comment]
> 0235150 adds the minimal documentation. I'm not sure this is quite the right interface, though. I wonder if it should be simply oghliner deploy dist.

I thought about it some more while implementing `oghliner offline` and decided that it does make sense for the root directory to be the direct argument of the command rather than an option/flag. So the _deploy_ command now looks like this:

```
09-28 15:07 > oghliner deploy --help

  Usage: deploy [options] [dir]

  deploy directory to GitHub Pages

  Options:

    -h, --help  output usage information
```

While the _offline_ command now looks like this:

```
09-28 15:07 > oghliner offline --help

  Usage: offline [options] [dir]

  offline the files in the directory by generating offline-worker.js script

  Options:

    -h, --help                        output usage information
    --file-globs [fileGlobs]          a comma-separated list of file globs to offline (default: '**/*')
    --import-scripts <importScripts>  a comma-separated list of additional scripts to import into offline-worker.js
```

I've also updated README.md to reflect this change. I think this can be closed now.
