### ISSUE TITLE
make Travis show output of deploy command by default

### ISSUE THREAD

**Issue by mykmelez** [mozilla/oghliner#19]
The output of the command that _configure_ adds to the _after_success_ script in .travis.yml is collapsed by default in Travis build logs. So you only see a single line like this when you first view a log ([like this one](https://travis-ci.org/mykmelez/mc-choir/builds/83798486)):

> 2.87s$ [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] && gulp deploy

You can see the rest of the log by clicking on the disclosure widget (expander arrow) to the left of that line item, after which you see the output of the command, which might look something like this:

> [23:31:35] Using gulpfile ~/build/mykmelez/mc-choir/gulpfile.js
> [23:31:35] Starting 'deploy'...
> [23:31:37] Finished 'deploy' after 1.91 s

But it would be better if Travis showed you that output by default, so you didn't have to expand the command to see it.

**Comment by marco-c** [comment]
Looks like Travis folds the output from the commands that aren't in the _scripts_ section.
