### ISSUE TITLE
await sync if it's already in progress when configure tells Travis to sync

### ISSUE THREAD

**Issue by mykmelez** [mozilla/oghliner#20]
When the _configure_ command doesn't find your repository in Travis, it tells Travis to sync it and then waits for the sync to complete (periodically polling Travis to find out the status of the sync). But if Travis is _already_ syncing your repository when _configure_ tells it to sync, then the _travis.users.sync.post_ call throws `{ message: 'Sync already in progress. Try again later.' }`, and the command doesn't catch that error, so it simply reports the error and dies:

> Checking the status of your repository in Travis…
> I didn't find your repository in Travis.  Syncing Travis with GitHub…
> { message: 'Sync already in progress. Try again later.' }

It should instead catch that error and call the _travisAwaitSyncing_ polling function in that case, just as it does in the case of the repository not being found.

**Comment by marco-c** [comment]
I have a patch for this, but I will wait #60 to be merged.
