### ISSUE TITLE
configure fails with "Endpoint temporarily disabled"

### ISSUE THREAD

**Issue by mykmelez** [mozilla/oghliner#215]
`oghliner configure` currently fails with the error `Endpoint temporarily disabled`:

```
11-19 14:43 > oghliner configure

Configuring Travis to auto-deploy to GitHub Pages…

Your repository has a single remote, origin.
Ok, I'll configure Travis to auto-deploy the origin remote (mykmelez/test-auth-github).

To check the status of your repository in Travis and authorize Travis to push
to it, I'll create GitHub personal access tokens, for which I need your GitHub
username and password (and two-factor authentication code, if appropriate).

ℹ For more information about GitHub personal access tokens, see:
    https://github.com/settings/tokens

Username: mykmelez
Password: 

× Checking credentials… error!

You're using two-factor authentication with GitHub.
Please enter the code provided by your authentication software.

Auth Code: 123456

✓ Checking credentials… done!
✓ Creating temporary GitHub token for getting Travis token… done!
  Getting Travis token… \Endpoint temporarily disabled
```

That causes the "live" tests to fail on Travis, for example on [this build job](https://travis-ci.org/mozilla/oghliner/jobs/92118032):

> 1) Configure "before each" hook for "activates inactive repository - displays message on failure":
>   Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
>    at tryCallOne (node_modules/promisify-node/node_modules/nodegit-promise/lib/core.js:37:12)
>    at node_modules/promisify-node/node_modules/nodegit-promise/lib/core.js:103:15
>    at flush (node_modules/promisify-node/node_modules/nodegit-promise/node_modules/asap/raw.js:50:29)
> 2) CLI interface, oghliner as a template should work:
>   Error: the number 1 was thrown, throw an Error :)
> 
> 3) CLI interface, oghliner as a template "after all" hook for "should work":
>   Error: the string "no access token supplied" was thrown, throw an Error :)
>    at tryCallOne (node_modules/promisify-node/node_modules/nodegit-promise/lib/core.js:37:12)
>    at node_modules/promisify-node/node_modules/nodegit-promise/lib/core.js:103:15
>    at flush (node_modules/promisify-node/node_modules/nodegit-promise/node_modules/asap/raw.js:50:29)
> 4) CLI interface, oghliner as a tool should work:
>   Error: the number 1 was thrown, throw an Error :)
> 
> 5) CLI interface, oghliner as a tool "after all" hook for "the CLI program should have an exit code != 0 if deploy fails":
>   Error: the string "no access token supplied" was thrown, throw an Error :)
>    at tryCallOne (node_modules/promisify-node/node_modules/nodegit-promise/lib/core.js:37:12)
>    at node_modules/promisify-node/node_modules/nodegit-promise/lib/core.js:103:15
>    at flush (node_modules/promisify-node/node_modules/nodegit-promise/node_modules/asap/raw.js:50:29)

Here's a nock recording of the transaction:

```
nock('https://api.travis-ci.org:443')
  .post('/auth/github', {"github_token":"…"})
  .reply(503, "Endpoint temporarily disabled", { connection: 'close',
  server: 'nginx',
  date: 'Thu, 19 Nov 2015 22:52:24 GMT',
  'content-type': 'application/json',
  'content-length': '29',
  status: '503 Service Unavailable',
  'access-control-allow-origin': '*',
  'access-control-allow-credentials': 'true',
  'access-control-expose-headers': 'Content-Type, Cache-Control, Expires, Etag, Last-Modified',
  'strict-transport-security': 'max-age=31536000',
  'x-endpoint': 'Travis::Api::App::Endpoint::Authorization',
  'x-pattern': '/github',
  'x-oauth-scopes': 'public',
  'x-accepted-oauth-scopes': 'public',
  vary: 'Accept,Accept-Encoding',
  'x-rack-cache': 'invalidate, pass',
  via: '1.1 vegur' });
```

The Past Incidents section of [Travis CI Status](https://www.traviscistatus.com/) has this to say:

> Nov 19, 2015
> /auth/github disabled due to continued DDoS
> Resolved - Login via the CLI is now working again. If you have a custom client using /auth/github, it might be misidentified as being part of the DDoS. If so, please get in touch via support@travis-ci.com.
> Nov 19, 19:04 UTC
> Investigating - We have been under a constant DDoS attack for the last two months. We are able to handle the load since we last addressed these attacks a few weeks ago. However, this seems to now be impacting the GitHub API using us as a proxy. We have therefore disabled the endpoint in question (/auth/github), which unfortunately means that it is temporarily impossible to log in on travis-ci.org via the CLI. If you are already logged in, you are not affected. Also, travis-ci.com and our web interface on travis-ci.org are not affected either.
> Nov 19, 18:52 UTC

So I'll email them. But we should also handle the errors better, both in UX (which should do more than just output the error and die) and in how we report/throw the error to the caller, per the test harness.

**Comment by mykmelez** [comment]
This is a direct link to the incident report: https://www.traviscistatus.com/incidents/bntk781kb8y8

**Comment by mykmelez** [comment]
I received a response from Travis that they've whitelisted the Oghliner user agent, but I'm still seeing an error (albeit a different one):

```
✓ Creating temporary GitHub token for getting Travis token… done!
  Getting Travis token… \you are currently not allowed to perform this request. please contact support@travis-ci.com.
```

I've contacted them again about the new error.

**Comment by marco-c** [comment]
The live tests are still failing (with a different error).

**Comment by marco-c** [comment]
https://github.com/mozilla/oghliner/pull/222
