### ISSUE TITLE
figure out how to test the *offline* command

### ISSUE THREAD

**Issue by mykmelez** [mozilla/oghliner#22]
We need to figure out how to test all the commands. _deploy_ and _configure_ might be harder, because they interact with servers; but _offline_ at least should be doable, so let's start there.

**Comment by marco-c** [comment]
We could use the test suite I built for https://github.com/marco-c/web-push (which currently only supports Linux, but should be easily extensible to support other OSes as well).

**Comment by marco-c** [comment]
The sw-precache tests are really basic, they only test whether the generated code is different or the same when using different/the same config options.

**Comment by marco-c** [comment]
I'll add some basic unit tests for now.
