### ISSUE TITLE
Show gzip size for results

### ISSUE THREAD

**Issue by digitarald** [mozilla/oghliner#225]
Currently the result of `Caching …` is showing the overall size: `Total precache size is about 500.37 kB for 25 resources.`

The stats could be extended to show the gzipped size, using a module like [gzip-size](https://www.npmjs.com/package/gzip-size), to give you a more real-life-network number.

**Comment by marco-c** [comment]
Could this cause confusion for the user? He might think that somehow `oghliner` is gzipping his resources.

**Comment by digitarald** [comment]
Yes, wording needs to be considered to avoid confusion, like "42kb if
served with gzipped".

On Sunday, November 29, 2015, Marco notifications@github.com wrote:

> Could this cause confusion for the user? He might think that somehow
> oghliner is gzipping his resources.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozilla/oghliner/issues/225#issuecomment-160473067.

## 

Web Craftsman | harald@mozilla.com | @digitarald [skype/irc/line] |
+1-650-963-6612 [wapp/telegram]
