### ISSUE TITLE
consider renaming module to something descriptive

### ISSUE THREAD

**Issue by mykmelez** [mozilla/oghliner#23]
We should consider renaming the module to something descriptive, like _offline-gh-pages_, per [these best practices for naming Node modules](https://github.com/mattdesl/module-best-practices#naming-conventions).

On the other hand, command-line utilities benefit from being short and sweet, and Oghliner exposes a command-line interface, in addition to its module interface. So perhaps it makes sense to keep the existing, compact name.

**Comment by wfwalker** [comment]
my first three suggestions:
- `sw-publish`, to emphasize publishing and service workers
- `gh-publish`, to emphasize github and publishing
- `ghp`, to emphasize github and publishing

**Comment by mykmelez** [comment]
The word "publish" is attractive and accurate. I originally used it when starting development of the project. But I changed to "deploy" because it appears to be the more conventional term, especially when describing the process for web _apps_ ("publish" may be a bit more common for web _sites_).

To wit: Travis CI's motto is "Test and deploy your code with confidence." And they feature "deployment" to a [variety of hosting providers](http://docs.travis-ci.com/user/deployment/), including GitHub Releases (although not GitHub Pages, which is why this project's _configure_ feature is useful).

**Comment by mykmelez** [comment]
Oghliner avoids describing Service Workers in its documentation because it intends to make them an implementation detail. Although I don't expect it'll support AppCache (like [Surge does](http://davidwalsh.name/dont-wait-serviceworker-adding-offline-support-oneline)) or another offlining API, it still shouldn't be necessary to know what a Service Worker is in order to offline your app and deploy it to GitHub Pages. So I'm loathe to change the name to something that references service workers.

**Comment by mykmelez** [comment]
> sw-publish, to emphasize publishing and service workers
> gh-publish, to emphasize github and publishing
> ghp, to emphasize github and publishing

These names have a strong "publish" bias, and they suggest that this project's value proposition is to deploy to GitHub Pages.

It's true that this project is carefully scoped, and that Node modules often follow the Unix philosophy, per https://github.com/mattdesl/module-best-practices#module-basics, to be "small programs that do one thing, do it well, and compose easily with other programs."

Nevertheless, this project's value proposition is actually that certain developers would benefit from a tool that composes a set of those "small programs" in a particular way to address a specific use case: deploying offline web apps to GitHub Pages. 

If a developer only wants to offline their app, then this project is not the right tool, since such a developer would be better served by a module like sw-precache that helps them accomplish that specific task (with configuration options for deployment targets other than GitHub Pages).

Conversely, if a developer only wants to deploy their app to GitHub Pages, then this project is similarly overkill, as they can integrate a module like gh-pages into their workflow for that purpose (although it's true that such a developer would still benefit from using this project to configure Travis auto-deploy).

So "offlining" is just as essential a feature as "deployment" to the project, and it would be misleading to emphasize only the latter in its name.

**Comment by delapuente** [comment]
I like `oghliner` because it is a pun between `off` and **G**it**H**ub. Isn't it? So it emphasizes the two core concepts of the project, deploying in GitHub and _offlining_ an application.

I think it's me who must change the name of `offliner` to something emphasizing the _life cycle for an application_ concept, let's say, `cyclapp` (I like the idea of an eye —a circle— depicting the _life cycle_) and thus, `oghliner` will be using `cyclapp` to  fulfil its purpose. So, if you agree, let's [rename offliner instead](https://github.com/delapuente/offliner/issues/4).

**Comment by mykmelez** [comment]
> I like oghliner because it is a pun between off and GitHub. Isn't it? So it emphasizes the two core concepts of the project, deploying in GitHub and offlining an application.

Yes, it's that pun! Which I figured was clever. But clever names are not always a great idea. When I was involved in naming projects for Mozilla Labs, clever names generally seemed like a good idea at the beginning of a project's lifecycle, because they were catchy and clever, but a bad idea further down the road, because they required an act of memorization to remember. Over time, I grew to appreciate descriptive project names, which both name and summarize the project.

These [module best practices](https://github.com/mattdesl/module-best-practices) suggest [naming conventions](https://github.com/mattdesl/module-best-practices#naming-conventions) that "generally favour clear and 'boring' names." I suspect the author is suggesting descriptive names.

**Comment by mykmelez** [comment]
> I think it's me who must change the name of offliner to something emphasizing the life cycle for an application concept, let's say, cyclapp (I like the idea of an eye —a circle— depicting the life cycle) and thus, oghliner will be using cyclapp to fulfil its purpose. So, if you agree, let's rename offliner instead.

It may indeed be worthwhile to change the name of _offliner_, but note that this issue is not about distinguishing between this project and _offliner_, it's about choosing the best name for this project! Even if you rename _offliner_, it might still make sense to rename this project, giving it a descriptive name.

**Comment by delapuente** [comment]
You're right, thinking about but I continue liking oghliner or _offliner_ for this project.

**Comment by mykmelez** [comment]
[npm-check-updates](https://www.npmjs.com/package/npm-check-updates) provides the _ncu_ command-line tool, which leads me to consider renaming this to _offline-github-pages_ and providing an _oghp_ command-line tool.

**Comment by mykmelez** [comment]
Also of note: despite the advice in that "best practices" document, popular npm packages aren't all descriptively named. Many are, like _change-case_, _github-slug_, _read-yaml_, and _travis-encrypt_; but there are plenty of others with figurative/idiomatic names, like _chalk_, _gulp_, _mocha_, and _nock_.

**Comment by mykmelez** [comment]
After thinking about it for a while, and implementing it in #184, I've decided that we shouldn't rename the project after all, because it's better to keep the names of the npm package and CLI tool the same; it's easier to talk about a project with a single word name; and the downsides of a figurative name aren't significant enough to override those benefits.
