### ISSUE TITLE
testConfigure tests are timing out on my new laptop

### ISSUE THREAD

**Issue by marco-c** [mozilla/oghliner#232]
I'm not sure whether this is due to the different characteristics of my new machine (that could uncover race conditions), to the different Node.js version or to the different npm module versions.

@mykmelez maybe you can try `rm -rf node_modules && npm install` and see if tests are still passing?

**Comment by mykmelez** [comment]
Hmm, I don't see this issue on my Mac. Here's the [log of `npm install && gulp test` after removing node_modules](https://github.com/mozilla/oghliner/files/47689/log.txt).

**Comment by marco-c** [comment]
Ok, then we can probably rule out the third option.
What version of Node.js are you currently using? I have 4.2.2.

**Comment by mykmelez** [comment]
> What version of Node.js are you currently using? I have 4.2.2.

I'm still on 0.12.7.

**Comment by marco-c** [comment]
They aren't timing out anymore...
