### ISSUE TITLE
improve .gh-pages-cache confirm prompt

### ISSUE THREAD

**Issue by mykmelez** [mozilla/oghliner#235]
The confirm prompt that asks if you want to add .gh-pages-cache to your .gitignore file doesn't specify a default option. It should specify one, probably "yes".

It's also very long, prone to wrapping in wide terminals, which is fine, except that it's inconsistent with other long strings, which we explicitly wrap. We should wrap this one too.

I might also add some additional explanatory text and make it a warning (complete with an icon), so it becomes something like:

```
⚠ The .gh-pages-cache directory is a temporary repository that I use
  to push changes to your gh-pages branch. It isn't in your .gitignore file,
  which means that Git will report it as an untracked file.

Do you want to add .gh-pages-cache to .gitignore (Y/n)?
```

**Comment by marco-c** [comment]
Oops, I didn't notice this issue, but had a similar idea.
I've opened #241 to add the default option, I'll update it with the rest of the changes you suggested.
