### ISSUE TITLE
make service worker ignore query parameters when matching URL to resource in cache

### ISSUE THREAD

**Issue by mykmelez** [mozilla/oghliner#24]
Oghliner doesn't set sw-precache's _ignoreUrlParametersMatching_ option, and that option's default value of `[/^utm_/]` means that sw-precache takes most query parameters into account when deciding whether or not to serve a resource from its cache.

That's a problem for apps like presentations using [Shower](https://github.com/shower/shower), which set query parameters like _full_ and _lang_ in client code to store state in a way that is bookmarkable. If a user loads an app page from a URL with a query parameter that wasn't present when the app was initially offlined, then the service worker will not serve the page from the cache, so the load will fail if the user is offline.

To solve that problem, _offline_ should set sw-precache's _ignoreUrlParametersMatching_ option to `[/./]` so it ignores all query parameters when matching URLs to fetch against URLs in its cache.

(Being able to do this for all apps automagically is one of the benefits of focusing on the GitHub Pages use case. Since GitHub Pages sites are always static, and query parameters never affect the result of a GET request for a GitHub Pages resource, we can always do this when offlining apps specifically for deployment on GitHub Pages.)

**Comment by marco-c** [comment]
As you said, this is specific to static sites. I agree we should only support deploying to GitHub Pages for now, but at the same time I think we shouldn't force anything on people who want to use oghliner only for offlining. So I'd make this configurable, maybe enabled by default, and we could show a warning when someone uses `deploy` without this option.
