### ISSUE TITLE
figure out how to test the deploy command

### ISSUE THREAD

**Issue by mykmelez** [mozilla/oghliner#34]
We need to figure out how to test the _deploy_ command.

We can create a local Git repository and bootstrap an app in it to deploy, but then there's the question of how to test that deployment pushes it to its _origin_ remote, which is normally on GitHub.

But _deploy_ doesn't actually depend on GitHub itself, only on there being an _origin_ "remote", which could presumably be another local repository. So it should be possible to test _deploy_ without a dependency on a GitHub server.

We would just need to create two local repositories, one of which has the other as its _origin_; build the app in the first repository; and then test that the _deploy_ command pushes the build output to the gh-pages branch in the _origin_ repository.

**Comment by marco-c** [comment]
Looks interesting, I'll take a stab at it.

**Comment by mykmelez** [comment]
Marco, these tests broke the next time I merged a change to master (https://travis-ci.org/mozilla/oghliner/builds/85199186), because the _tmp_ dir was apparently preserved across builds:

> 2) Deploy should update the gh-pages branch in the origin repo and publish files to it:
>     Error: EEXIST, file already exists 'tmp'
>      at Error (native)
>      at Object.fs.mkdirSync (fs.js:747:18)
>      at Context.<anonymous> (test/testDeploy.js:49:8)

**Comment by brendandahl** [comment]
The temp folder/file creation library I used in https://github.com/mozilla/oghliner/pull/63/files#diff-c792d04edfea01487109cfd6450c9ef8R4 worked pretty well.

**Comment by marco-c** [comment]
@mykmelez I think it was a timeout, which then caused the "tmp" directory to be preserved and thus the second test to fail.
It's likely that the test could actually need more time, as in this successful build (https://travis-ci.org/mozilla/oghliner/builds/85199186, which is yours retriggered) the test took 673ms (which is relatively close to the current timeout of 2 seconds).

Let's file a new issue if it happens again.
I'll also submit a PR to avoid failing following tests when the first runs out of time.
