### ISSUE TITLE
make it easier to configure auto-deploy for *upstream* repo

### ISSUE THREAD

**Issue by mykmelez** [mozilla/oghliner#54]
The _configure_ command assumes that you want to auto-deploy merges to the _master_ branch on the _origin_ remote.

But for projects with multiple contributors, it's common for a user to fork the original repo and clone their fork, such that the _origin_ remote points to their fork, and then create an _upstream_ remote for the original repo, as described in GitHub's [Fork A Repo](https://help.github.com/articles/fork-a-repo/) documentation.

And it's actually more interesting to configure auto-deploy for the original, upstream repo, since that's the one in which people will more often merge changes via pull requests and want those merges to trigger auto-deploy.

But it's hard to do that right now. You have to either temporarily rename your remotes so the original remote is named _origin_ (which actually sounds like a better name for it, although it is unconventional) or clone the original remote and configure that clone.

We should make it easier to configure auto-deploy for the _upstream_ repo.

For example, we could prompt the user to choose the remote for which to configure auto-deploy, selecting the _upstream_ remote by default if one is defined.

(A related problem is that you can't configure a repo to auto-deploy both the original repo and a fork, since the encrypted GitHub auth token in .travis.yml is repo-specific, and there can be only one auth token in the Travis build environment variables. But that's a different issue.)

**Comment by marco-c** [comment]
There's an undocumented option in the `gh-pages` module that should make this easy: https://github.com/tschaub/gh-pages/blob/ab5a1bef7829bacd95e6034dd8f4354df665f2ba/lib/index.js#L64

**Comment by marco-c** [comment]
https://github.com/tschaub/gh-pages/pull/24 would allow to do this.

**Comment by marco-c** [comment]
Fixed by #165.
