### ISSUE TITLE
Travis auto-deploy fails with "invalid username or password"

### ISSUE THREAD

**Issue by mykmelez** [mozilla/oghliner#77]
Travis auto-deploy appears to have regressed. After reconfiguring this repository, an auto-deploy attempt fails with "Invalid username or password":

> 2.05s$ [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] && gulp deploy
> [20:39:53] Using gulpfile ~/build/mozilla/oghliner/gulpfile.js
> [20:39:53] Starting 'deploy'...
> [20:39:53] Deploying "update GitHub token for Travis auto-deploy"
> [20:39:54] 'deploy' errored after 917 ms
> [20:39:54] ProcessError: remote: Invalid username or password.
> fatal: Authentication failed for 'https://github.com/mozilla/oghliner.git/'
>    at ChildProcess.<anonymous> (/home/travis/build/mozilla/oghliner/node_modules/gh-pages/lib/git.js:48:23)
>    at ChildProcess.emit (events.js:110:17)
>    at maybeClose (child_process.js:1015:16)
>    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
> Done. Your build exited with 0.

**Comment by mykmelez** [comment]
This is the build where it fails: https://travis-ci.org/mozilla/oghliner/builds/85610329

**Comment by marco-c** [comment]
Fixed by #91.
