### ISSUE TITLE
use yargs (or minimist) after all

### ISSUE THREAD

**Issue by mykmelez** [mozilla/oghliner#81]
https://github.com/mozilla/oghliner/commit/c19f3ff70d52cdaeb6aa2dc7db9ae47332ab7296 introduced gulp.env usage to gulpfile.js, but gulp complains: "gulp.env has been deprecated. Use your own CLI parser instead. We recommend using yargs or minimist." So I guess we should use yargs (or minimist) after all. Note that cli.js uses [commander](https://www.npmjs.com/package/commander), but that seems like overkill and a mismatch for this use case.

**Comment by marco-c** [comment]
Oops, I didn't notice the deprecation message!
