### ISSUE TITLE
redesign Oghliner website

### ISSUE THREAD

**Issue by mykmelez** [mozilla/oghliner#95]
The Oghliner website at https://mozilla.github.io/oghliner/ was designed using the GitHub Pages generator, and it could use a redesign (both graphic design and information design) in order to better convey what the project is about and how to go about using it.

This used to be identical to #7, because we were using the website as the template for bootstrapping new apps. But now we've separated those two things, so the website is in app/, while the _bootstrap_ command uses the template in templates/. Thus redesigning the website is now a separate concern from redesigning the template.

**Comment by darkwing** [comment]
What do we think about using MDN as the Oghliner website, creating a similar design to this:

https://developer.mozilla.org/en-US/Firefox

If we prefer the app content live within the repo, I can mock up a site similar to the Firefox download page:  https://www.mozilla.org/en-US/firefox/new/

**Comment by marco-c** [comment]
I think @darkwing is taking care of this in #117.

**Comment by darkwing** [comment]
@mykmelez Can we close this or do we have more specific design changes?

**Comment by marco-c** [comment]
The only missing thing is the information re-design.
